---
# BACKEND SETUP

- hosts: tag_Name_backend
  gather_facts: true
  become: yes

  roles:
    - backend

# FRONTEND SETUP

- hosts: tag_Name_fronted
  gather_facts: true
  become: yes

  roles:
    - frontend
